name: macOS Build CI

on: [push, pull_request]

jobs:
  macos-build:
    runs-on: macos-latest
    name: macOS Build
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Update Brew
        run: brew update
      #- name: Update Brew
        #run: brew upgrade
      - name: Install Deps
        run: brew install llvm@17 libpng tcl-tk harfbuzz freetype fontconfig cairo icu4c glib zlib bzip2
      - name: macOS build test
        run: make
